site_name: EDIUG-SC-CGIB
theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - search
  - git-revision-date
nav:
  - 主页: index.md
  - 贡献: 
    - 贡献指南: 贡献/贡献指南.md
    - 课程模板: 贡献/课程模板.md
  - 大一上:
    - 出版概论: 大一上/出版概论/index.md
    - 大国出版: 大一上/大国出版/index.md
    - 大学生心理健康: 大一上/大学生心理健康/index.md
    - 大学英语一级: 大一上/大学英语一级/index.md
    - 思想道德与法治: 大一上/思想道德与法治/index.md
    - 程序设计基础: 大一上/程序设计基础/index.md
    - 线性代数: 大一上/线性代数/index.md
    - 高等数学 - Ⅰ: 大一上/高等数学 - Ⅰ/index.md
    - 军事理论: 大一上/军事理论/index.md
    - 晚自习: 大一上/晚自习/index.md
  - 大一下:
    - 劳动教育: 大一下/劳动教育/index.md
  - 教师风评: 
    - 基础教育学院:
      - 数学部:
        - 杜云飞: 教师风评/基础教育学院/数学部/杜云飞.md
        - 田益民: 教师风评/基础教育学院/数学部/田益民.md
        - 王梦雨: 教师风评/基础教育学院/数学部/王梦雨.md
      - 英语部:
        - 魏芳: 教师风评/基础教育学院/英语部/魏芳.md
    - 信息工程学院:
      - 齐亚莉: 教师风评/信息工程学院/齐亚莉.md
      - 王克蒙: 教师风评/信息工程学院/王克蒙.md
      - 徐长波: 教师风评/信息工程学院/徐长波.md
      - 王佳: 教师风评/信息工程学院/王佳.md
  - 校园服务:
    - 校车时刻表: 校园服务/bbs-lnf.md
    - 校园网: 校园服务/bigc_wifi.md
  - 校园生活:
    - 食堂: 
      - 康庄食堂:
        - 二楼民族餐厅:
          - 小火锅: 校园生活/食堂/康庄食堂/二楼民族餐厅/小火锅.md
          - 面包房: 校园生活/食堂/康庄食堂/二楼民族餐厅/面包房.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  # ✅ 用这个代替 strikethrough 支持 ~删除线~
repo_url: https://github.com/LeNotFound/EDIUG-SC-CGIB
repo_name: LeNotFound/EDIUG-SC-CGIB
